### ISSUE TITLE
Errors on Console: google-cast-button

### ISSUE THREAD

**Issue by Wilsonruan** [brightcove/react-player-loader#112]
I seem to be getting an error on the console when there are more than one video.  We don't want chrome-cast. Can we prevent this error from appearing?

cast_framework.js:64 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "google-cast-button" has already been used with this registry
    at http://www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js:64:39
    at http://www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js:69:234
(anonymous) @ cast_framework.js:64
(anonymous) @ cast_framework.js:69

**Comment by MeVimalkumar** [comment]
@Wilsonruan what exact changes you made to get rid of this issue?

**Comment by anass05** [comment]
@Wilsonruan would you please share your fix?

**Comment by Wilsonruan** [comment]
@MeVimalkumar, @anass05.  I reach out to my media team.  It was a setting in our data-player. I asked to disable google-cast-button.  The problem is if you have the google-cast-button active and currently not used.  It will give us an error.
