### ISSUE TITLE
Is there an ETA when version 1.5.0 will be push out to NPM

### ISSUE THREAD

**Issue by GerryP2** [brightcove/react-player-loader#123]
Would be great to have the [support strict mode]

**Comment by dannydebug** [comment]
Agreed. Strict mode issue is pretty annoying and using an iframe as `embedType` does have its limitations. Would appreciate any updates on this!

**Comment by brianlaframboise** [comment]
This is affecting me, and I've confirmed that `1.5.0` fixes the double render in strict mode issue. It looks to me like that version was meant to be released, but the actual publish to npm was missed? If so, seems like a quick fix. I would love to see this released asap.

**Comment by chrissnyder2337** [comment]
@brianlaframboise I think you are right... the step of publishing to npm was just missed.

**Comment by brianlaframboise** [comment]
Also, please confirm, but I believe this should close #102

**Comment by brianlaframboise** [comment]
I see that 1.5.0 is now released to npm: https://www.npmjs.com/package/@brightcove/react-player-loader/v/1.5.0. I haven't personally tested it yet but I presume it contains the strict mode fix.
