### ISSUE TITLE
Document React version requirements

### ISSUE THREAD

**Issue by tjaneczko** [brightcove/react-player-loader#14]
The use of `createRef` means this can't be used in React versions < 16.3.  This limitation should be documented (or support for older versions of React should be added)

**Comment by misteroneill** [comment]
Thanks @tjaneczko!

I'd be curious to know what the alternative is. I'm not very React-savvy, myself.

**Comment by tjaneczko** [comment]
@misteroneill In previous versions of react, you simply attached a function to the `ref` prop on the rendered element which would set get the reference node:
```js
class MyComponent extends React.Component {
  nodeRef = null;
  setNodeRef = ref => this.nodeRef = ref;

  render () {
    return (
      <div ref={this.setNodeRef}/>
    );
  }
}
```

This has some drawbacks, which is why they added the whole new refs API, but unfortunately that means that libraries that want to support React versions less than 16.3 either need to implement a fallback or just not use the new refs API.
