### ISSUE TITLE
Customisation (removal?) of wrapping `div`

### ISSUE THREAD

**Issue by nathanielw** [brightcove/react-player-loader#25]
Hi, thanks for this component! This is a bit of a mix of a question and a feature request. I'm needing to customise the element that wraps the video-js component - i.e. the `div` generated in the component's render method. Specifically I'm wanting to add a class to the element or remove the element completely (so that the video-js component is a direct child of whatever I choose to place it within).

I've got this working with a forked version of the component where I've changed the hardcoded `refNodeInsert` option to  `'replace'`. The readme mentions that that option is needed internally, hence the inability to pass it in. However, given `replace` doesn't appear to be causing any issues, is there some case I'm overlooking that makes `append` more suitable as the hardcoded value?

Thanks!

**Comment by misteroneill** [comment]
I think we could definitely make some improvements to the component to make the wrapper element more customizable - good idea!

However, eliminating the wrapper element is not advisable. The `video-js` element is controlled by Video.js and not by React. The React component that contains the Video.js player needs to be able to dispose and re-create the player during the React component mount/unmount cycle.

**Comment by misteroneill** [comment]
@nathanielw The ability to customize the wrapper element was added in 1.2.0 - feel free to give it a try!

**Comment by nathanielw** [comment]
Thanks @misteroneill! I've just updated and it's working nicely for what we needed :)
