### ISSUE TITLE
Component doesn't re-render when props change

### ISSUE THREAD

**Issue by alex-barstow** [brightcove/react-player-loader#38]
Once the player component has been rendered once, it won't be re-rendered if the props change.

**Comment by misteroneill** [comment]
A good example of this is changing the `videoId` prop.

**Comment by alex-barstow** [comment]
Reason could be because `playerLoader()` is only invoked [once](https://github.com/brightcove/react-player-loader/blob/master/src/index.js#L113) (in `componentDidMount()`), and doesn't get called again when the component updates. The solution may be to make a fresh `playerLoader()` call in a `componentDidUpdate()` lifecycle method. More investigation required.

**Comment by gkatsev** [comment]
I thought this was by design? If the component needs to be re-rendered then the player needs to be disposed and re-created which will can cause issues if a user has kept a reference to the old player.

**Comment by alex-barstow** [comment]
At least in the case of a changing `videoId` prop, we could conceivably just change the source without disposing the player.
