### ISSUE TITLE
ads issue 

### ISSUE THREAD

**Issue by sarangan** [brightcove/react-player-loader#41]
video could not play video after ads finished loading. it happens in iphone devices only. after ads the player "ended" event got fired. any idea how to resolve this?

**Comment by misteroneill** [comment]
* Do you have a reduced test case you could provide?
* Is the issue reproducible in your Brightcove Player outside of the React Player Loader - or is it specific to this tool?
  * If the issue is reproducible outside this tool, please open a support case with Brightcove.

**Comment by sarangan** [comment]
Hi @misteroneill the issue has been resolved by Bright Cove team. thanks
