### ISSUE TITLE
Demo fails

### ISSUE THREAD

**Issue by janeeisenstein** [brightcove/react-player-loader#55]
After following the README instructions for installing and running the demo, navigating to http://localhost:9999/ results in:
```
Nothing will appear below because this page uses an invalid account ID by default.

Open the console and use window.customApp.setState({}) to try changing props.
```
Just running `npm start` results in several reports of `ERROR: Error: mock catalog request failure` 

The complete `npm start` output is attached.
[react-player-loader-npm-start.txt](https://github.com/brightcove/react-player-loader/files/3542367/react-player-loader-npm-start.txt)

**Comment by misteroneill** [comment]
@janeeisenstein Thanks for the report.

Those messages are normal and are a result of testing certain failure cases. If you run `npm start` and navigate to http://localhost:9999/test/debug.html you will see that the tests are passing even though those error messages are logged to the console.

Sorry for any confusion!
