### ISSUE TITLE
VIDEOJS ERROR

### ISSUE THREAD

**Issue by softweave** [brightcove/react-player-loader#56]
Using the account and video IDs of this player with your component results in a VIDEOJS ERROR and a black player:     https://players.brightcove.net/13421203001/default_default/index.html?videoId=5616411953001

Opening this codepen in Chrome demonstrates the problem: https://codepen.io/softweave/pen/pozrjoX

**Comment by misteroneill** [comment]
@softweave Thanks for the report.

It looks like the player in question is v5.28.1, which is [not supported by the underlying player-loader library](https://github.com/brightcove/player-loader#brightcove-player-support). You'll need to update to v6.x in order to use this library.
